Add gradients utility
vigetlabs/tailwindcss-plugins pull request #5
Opened 2020-04-15 15:42 UTC by mzlock

2020-04-15 17:38 UTC, gregkohn requested changes
tiny change but 👏

2020-04-15 17:38 UTC, gregkohn commented on plugins/gradients/README.md
> +    background-image: linear-gradient(90deg, ${theme('colors.blue.400')} 50%, transparent);
I guess the color would also be computed to something? 🤷‍♂️small thing

2020-04-15 17:38 UTC, gregkohn commented on plugins/gradients/index.js
> +module.exports = () => ({ addUtilities, theme, variants }) => {
We just decided to use the new `plugin()` API that 1.2 introduced -- just means importing that fn and wrapping this export in it (can also skip the extra `() =>`). For now it doesnt do all that much -- mainly handles the invoking in `tailwind.config.js` automatically so no longer need to include `()` there -- but it allows some other features and feels like the "right" way to do it now

Example here: https://github.com/vigetlabs/tailwindcss-plugins/blob/master/plugins/rect/index.js

2020-04-15 18:50 UTC, mzlock commented
@gregkohn @jeremyfrank - any preference or opinion on singular versus plural language for these?

- Classname: `.gradient-key` (singular)
- Config: `gradients: {}` (plural)
- Variants: `gradients: []` (plural)

2020-04-16 00:47 UTC, jeremyfrank approved these changes
Small tweak then 👍

2020-04-16 00:47 UTC, jeremyfrank commented on plugins/gradients/index.js
> +      [`.gradient-${key}`]: {
Might also want to use the `e` method to escape the class names, just incase someone tries to name the keys with fractions, e.g. `gradient-blue-1/2`. Actually I think the docs recommend always wrapping user provided selectors this way as a safeguard.

2020-04-16 00:47 UTC, jeremyfrank commented on plugins/gradients/index.js
> +      [`.gradient-${key}`]: {
https://tailwindcss.com/docs/plugins/#escaping-class-names

2020-04-16 00:51 UTC, jeremyfrank commented
Hmm, singluar vs plural, good question. Looking at the default config, maybe singular for all? Don't feel too strongly about it though.
https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js

2020-04-16 14:59 UTC, gregkohn commented
@mzlock good catch, I would definitely say to go with `singular`, that's convention as @jeremyfrank pointed out

2020-05-04 14:38 UTC, mzlock commented
@gregkohn @jeremyfrank - Updated! What's the process for merging and getting changes on NPM? Should I let one of y'all merge and version things?

2020-05-04 14:41 UTC, gregkohn approved these changes

2020-05-04 14:42 UTC, gregkohn commented
ah dang, one last thing @mzlock! can you add the gradients link to the main README?

2020-05-04 15:07 UTC, merged

2020-05-05 00:11 UTC, jeremyfrank commented
Nice! No official process for when to put out a new version and publish to npm. Greg and I have just been handling that whenever we can.